Repository WildCodeSchool/2022-03-php-orleans-project-paleolife, pull requests merged in 2022-07, with the labels that each got.

#188 S4US20_welcome_user
  templates/client/index.html.twig
Labels: Reviewed, Corrections done

#196 S4US26_date_view
  migrations/Version20220628141015.php
  src/DataFixtures/ClientFixtures.php
  src/Entity/Client.php
  templates/client/index.html.twig
Labels: Reviewed, Conflit resolved

#195 card_entreprise
  assets/images/photoentreprisepanoramic.jpg
  templates/home/index.html.twig
Labels: Reviewed, Conflit resolved

#216 add session and service in admin
  migrations/Version20220704074018.php
  src/Controller/ClientController.php
  src/DataFixtures/ExerciseFixtures.php
  src/DataFixtures/SessionFixtures.php
  src/Entity/Client.php
  src/Entity/Session.php
  templates/adminClient/_form.html.twig
  templates/adminClient/edit.html.twig
Labels: Reviewed

#230 Dev to main
  .gitignore
  assets/images/photoentreprisepanoramic.jpg
  assets/images/placeholderClient.jpg
  assets/styles/client.scss
  assets/styles/variable.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/packages/vich_uploader.yaml
  migrations/Version20220623143837.php
  migrations/Version20220628141015.php
  migrations/Version20220704074018.php
  migrations/Version20220704104515.php
  migrations/Version20220704120106.php
  migrations/Version20220704120504.php
  migrations/Version20220705133709.php
  src/Controller/ClientController.php
  src/Controller/LoginController.php
  src/Controller/RegistrationController.php
  src/Controller/UserController.php
  src/DataFixtures/ClientFixtures.php
  src/DataFixtures/ExerciseFixtures.php
  src/DataFixtures/MeasurementClientFixtures.php
  src/DataFixtures/MeasurementFixtures.php
  src/DataFixtures/PhotoAfter.jpg
  src/DataFixtures/PhotoBefore.jpg
  src/DataFixtures/ServiceFixtures.php
  src/DataFixtures/SessionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Client.php
  src/Entity/Measurement.php
  src/Entity/MeasurementClient.php
  src/Entity/Service.php
  src/Entity/Session.php
  src/Entity/User.php
  src/Form/ProfilClientType.php
  src/Form/ServiceType.php
  src/Repository/MeasurementClientRepository.php
  src/Repository/MeasurementRepository.php
  symfony.lock
  templates/adminClient/_form.html.twig
  templates/adminClient/edit.html.twig
  templates/client/_form.html.twig
  templates/client/edit.html.twig
  templates/client/index.html.twig
  templates/component/_admin_navbar.html.twig
  templates/component/_footer.html.twig
  templates/component/_navbar.html.twig
  templates/component/_navbar_client.html.twig
  templates/home/index.html.twig
  templates/registration/register.html.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: Reviewed

#229 add comment in client
  migrations/Version20220705103031.php
  src/Controller/ClientController.php
  src/DataFixtures/SessionFixtures.php
  src/Entity/Session.php
  templates/client/_comment_form.html.twig
  templates/client/index.html.twig
Labels: Reviewed, Corrections done, Conflit resolved

#228 S4 us61 view session for client
  assets/styles/client.scss
  src/DataFixtures/ClientFixtures.php
  src/DataFixtures/ExerciseFixtures.php
  src/DataFixtures/MeasurementClientFixtures.php
  src/DataFixtures/SessionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Client.php
  src/Entity/Session.php
  templates/client/index.html.twig
Labels: Reviewed, Corrections done, Conflit resolved

#234 S4US57ModalHome
  assets/images/PlaquetteDeVente.jpg
  assets/images/PlaquetteDeVente.pdf
  templates/home/index.html.twig
Labels: Reviewed, Corrections done

#236 S04US58AddPDF
  templates/home/index.html.twig
Labels: Reviewed

#244 change photo pres
  assets/images/photopres.jpeg
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#232 S4 us69 sidebar client
  assets/styles/client.scss
  templates/client/index.html.twig
Labels: Reviewed, Conflit resolved

#238 S4 us70 upload image
  config/packages/vich_uploader.yaml
  migrations/Version20220706102258.php
  src/DataFixtures/ServiceFixtures.php
  src/DataFixtures/personnal0.jpg
  src/DataFixtures/personnal1.jpg
  src/Entity/Service.php
  src/Form/ServiceType.php
  templates/home/index.html.twig
Labels: Reviewed, Conflit resolved

#235 testboutontop
  templates/component/_footer.html.twig
Labels: Reviewed

#241 F ix add session admin
  src/Controller/SessionController.php
  src/Entity/Session.php
  templates/adminClient/edit.html.twig
Labels: Reviewed

#247 supp close button and add svg
  templates/home/index.html.twig
Labels: Reviewed

#243 add button delete
  src/Controller/SessionController.php
  src/Entity/Session.php
  templates/adminClient/edit.html.twig
  templates/session/show.html.twig
Labels: Reviewed, Conflit resolved

#237 fix style page client
  assets/styles/client.scss
  templates/client/_comment_form.html.twig
  templates/client/index.html.twig
Labels: Reviewed, Conflit resolved

#254 add admin in route profil
  src/Controller/ClientController.php
Labels: Reviewed

#255 edit measurement
  src/Controller/MeasurementController.php
  templates/measurement/edit.html.twig
  templates/measurement/index.html.twig
Labels: Reviewed

#259 add nutrition in client view
  templates/client/index.html.twig
Labels: Reviewed

#256 S04 us71delete crud measure
  src/Controller/MeasurementController.php
  src/Entity/Measurement.php
  templates/measurement/_delete_form.html.twig
  templates/measurement/index.html.twig
Labels: Reviewed, Conflit resolved

#264 fixClientNutrition
  templates/client/index.html.twig
Labels: Reviewed

#265 d-none d-md-block sidebar
  templates/client/index.html.twig
Labels: Reviewed

#266 Fix style title home
  assets/images/greenLogo.png
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#262 Fix style admin client
  templates/adminClient/edit.html.twig
  templates/session/_delete_form.html.twig
Labels: Reviewed, Corrections done, Conflit resolved

#267 S4 us50 edit nutrition
  templates/adminClient/edit.html.twig
  templates/nutrition_meal/_form.html.twig
  templates/nutrition_meal/edit.html.twig
Labels: Reviewed, Corrections done, Conflit resolved

#274 create button delete nutrition in admin client
  src/Controller/NutritionMealController.php
  templates/adminClient/edit.html.twig
  templates/nutrition_meal/_delete_form.html.twig
  templates/nutrition_meal/index.html.twig
Labels: Reviewed, Corrections done, Conflit resolved

#296 Fix title presentation
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed, Fix

#297 fix scroll horizontal
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, Fix

#301 Fix required service edit
  src/Form/ServiceType.php
Labels: Reviewed, Fix

#302 fix placeholder in form registration
  src/Form/RegistrationFormType.php
Labels: Reviewed, Fix

#303 Fix required form in ContactType for telephone
  src/Entity/Contact.php
  src/Form/ContactType.php
Labels: Reviewed, Fix

#284 fixEmailContact
  assets/images/Plaquette de vente Seb v3.pdf
  templates/email.html.twig
  templates/email/email_user_to_admin.html.twig
Labels: Reviewed, Fix

#299 Fix mensuration unity
  templates/client/_form.html.twig
Labels: Reviewed, Corrections done, Fix

#305 fix_color_dark_client
  templates/client/index.html.twig
Labels: Reviewed, Fix

#307 fix_admin_delete_measurement_redirection
  src/Controller/MeasurementController.php
Labels: Reviewed, Fix

#308 fix_admin_edit_measurement_redirection
  src/Controller/MeasurementController.php
Labels: Reviewed, Fix

#306 fix_admin_add_measurement_redirection
  src/Controller/MeasurementController.php
Labels: Reviewed, Fix

#304 fix responsive contact
  templates/contact/index.html.twig
Labels: Reviewed, Corrections done, Fix

#315 create message falsh
  src/Controller/ServiceController.php
  src/Controller/UserController.php
Labels: Reviewed, Fix

#319 fix button delete
  src/Entity/Service.php
Labels: Reviewed

#322 S4US10_law_mention
  src/Controller/LawMentionController.php
  templates/component/_footer.html.twig
  templates/lawMention/index.html.twig
Labels: Reviewed

#321 add name in form
  src/Controller/SessionController.php
  templates/nutrition_meal/edit.html.twig
  templates/nutrition_meal/new.html.twig
  templates/session/edit.html.twig
  templates/session/new.html.twig
Labels: Reviewed, Fix

#325 fix_button_login_registration_contact
  templates/contact/index.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, Fix

#326 correction button return in edit nutrition
  src/Form/UserType.php
  templates/nutrition_meal/_form.html.twig
Labels: Reviewed, Fix

#330 style sidebar icon + padding
  templates/adminClient/edit.html.twig
Labels: Reviewed

#332 add margin in form
  templates/adminClient/_form.html.twig
Labels: Reviewed

#333 fix table style
  templates/adminClient/edit.html.twig
Labels: Reviewed, Fix

#324 fixReadMe
  README.md
Labels: Reviewed

#334 fix redirection button edit in nutrition
  src/Controller/NutritionMealController.php
Labels: Reviewed, Fix

#338 Dev to main
  README.md
  assets/images/Plaquette de vente Seb v3.pdf
  assets/images/greenLogo.png
  src/Controller/LawMentionController.php
  src/Controller/MeasurementController.php
  src/Controller/NutritionMealController.php
  src/Controller/ServiceController.php
  src/Controller/SessionController.php
  src/Controller/UserController.php
  src/Entity/Contact.php
  src/Entity/Service.php
  src/Form/ClientType.php
  src/Form/ContactType.php
  src/Form/RegistrationFormType.php
  src/Form/ServiceType.php
  src/Form/UserType.php
  templates/adminClient/_form.html.twig
  templates/adminClient/edit.html.twig
  templates/client/_form.html.twig
  templates/client/index.html.twig
  templates/component/_admin_navbar.html.twig
  templates/component/_footer.html.twig
  templates/component/_measurement_client.html.twig
  templates/contact/index.html.twig
  templates/email.html.twig
  templates/email/email_user_to_admin.html.twig
  templates/home/index.html.twig
  templates/lawMention/index.html.twig
  templates/login/index.html.twig
  templates/nutrition_meal/_delete_form.html.twig
  templates/nutrition_meal/_form.html.twig
  templates/nutrition_meal/edit.html.twig
  templates/nutrition_meal/index.html.twig
  templates/nutrition_meal/new.html.twig
  templates/registration/register.html.twig
  templates/session/_delete_form.html.twig
  templates/session/edit.html.twig
  templates/session/new.html.twig
Labels: Reviewed

#340 correction scroll horizontal
  templates/adminClient/edit.html.twig
Labels: Reviewed, Fix

#348 add retour in admin client
  templates/nutrition_meal/edit.html.twig
  templates/nutrition_meal/new.html.twig
  templates/session/edit.html.twig
  templates/session/new.html.twig
Labels: Reviewed, Fix

#337 fix_erreur_login
  src/Entity/User.php
  templates/component/_flashes.html.twig
  templates/login/index.html.twig
Labels: Reviewed, Fix

#352 fix button delete
  src/Entity/Client.php
Labels: Reviewed, Fix

#353 correction inscription
  src/Entity/User.php
Labels: Reviewed, Fix

#354 fix style
  templates/session/_form.html.twig
  templates/session/new.html.twig
Labels: Reviewed, Fix

#358 fix redirection
  src/Controller/ClientController.php
Labels: Reviewed, Fix

#360 Dev to main
  migrations/Version20220711145927.php
  src/Controller/ClientController.php
  src/DataFixtures/ExerciseFixtures.php
  src/Entity/Client.php
  src/Entity/Exercise.php
  src/Entity/User.php
  src/Form/ExerciseType.php
  templates/adminClient/edit.html.twig
  templates/component/_flashes.html.twig
  templates/login/index.html.twig
  templates/nutrition_meal/edit.html.twig
  templates/nutrition_meal/new.html.twig
  templates/session/_form.html.twig
  templates/session/edit.html.twig
  templates/session/new.html.twig
Labels: Reviewed

#349 fix_responsive_client
  assets/styles/client.scss
  templates/client/_comment_form.html.twig
  templates/client/index.html.twig
  templates/component/_measurement_client.html.twig
Labels: Reviewed, Corrections done, Fix

#399 fixReadConjug
  README.md
Labels: Reviewed, Fix

#320 touche de vert page home
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed, Corrections done, Fix, Conflit resolved

#401 add border and maj
  src/Form/ClientType.php
  templates/adminClient/_form.html.twig
Labels: Reviewed, Fix

#404 fixresponsive edit profil
  templates/client/_form.html.twig
  templates/client/edit.html.twig
  templates/client/index.html.twig
Labels: Reviewed, Fix

#405 fix-redirection new session
  src/Controller/SessionController.php
Labels: Reviewed, Fix

#406 fix trad fr
  src/Form/SessionType.php
Labels: Reviewed, Fix

#407 favicon feuille
  templates/adminBase.html.twig
  templates/base.html.twig
Labels: Reviewed, Fix

#408 fix faute
  src/Controller/ClientController.php
Labels: Reviewed, Fix

#410 redirection and change message flash
  src/Controller/NutritionMealController.php
Labels: Reviewed, Fix

#411 fix style button
  assets/collection.js
  templates/session/_form.html.twig
Labels: Reviewed, Fix

#403 fix delete session in admin client
  src/Controller/SessionController.php
Labels: Reviewed, Corrections done, Fix

#412 fix route admin client
  src/Controller/ClientController.php
Labels: Reviewed, Fix

#414 space title button'
  templates/adminClient/edit.html.twig
Labels: Reviewed, Fix

#415 fix activation button
  templates/user/index.html.twig
Labels: Reviewed, Fix

#416 fix edit mensuration
  src/Entity/Client.php
  src/Entity/MeasurementClient.php
Labels: Reviewed, Fix

#413 Fix route trad
  src/Controller/ClientController.php
  src/Controller/ExerciseController.php
  src/Controller/LoginController.php
  src/Controller/MeasurementController.php
  src/Controller/NutritionMealController.php
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/Controller/ServiceController.php
  src/Controller/SessionController.php
  src/Controller/UserController.php
  src/Entity/Client.php
Labels: Reviewed, Fix, Conflit resolved

#417 fixRedirectMDP
  templates/reset_password/email.html.twig
Labels: Reviewed, Fix

#418 testw3c
  templates/home/index.html.twig
Labels: Reviewed, Fix

#420 align button
  templates/adminClient/edit.html.twig
Labels: Reviewed, Fix

#421 add unity after value
  templates/component/_measurement_client.html.twig
Labels: Reviewed, Fix

#423 add flash
  src/Controller/ClientController.php
Labels: Reviewed, Fix

#422 Fix email
  src/Controller/ResetPasswordController.php
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
Labels: Reviewed, Fix, Conflit resolved

#424 create error page
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Reviewed, Fix

#425 fix home style
  assets/styles/home.scss
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Fix

#426 Dev to main
  README.md
  assets/collection.js
  assets/styles/client.scss
  assets/styles/home.scss
  src/Controller/ClientController.php
  src/Controller/ExerciseController.php
  src/Controller/LoginController.php
  src/Controller/MeasurementController.php
  src/Controller/NutritionMealController.php
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/Controller/ServiceController.php
  src/Controller/SessionController.php
  src/Controller/UserController.php
  src/Entity/Client.php
  src/Entity/MeasurementClient.php
  src/Form/ClientType.php
  src/Form/SessionType.php
  templates/adminBase.html.twig
  templates/adminClient/_form.html.twig
  templates/adminClient/edit.html.twig
  templates/base.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/client/_comment_form.html.twig
  templates/client/_form.html.twig
  templates/client/edit.html.twig
  templates/client/index.html.twig
  templates/component/_measurement_client.html.twig
  templates/home/index.html.twig
  templates/measurement/_delete_form.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/service/_delete_form.html.twig
  templates/service/index.html.twig
  templates/session/_form.html.twig
  templates/session/edit.html.twig
  templates/user/index.html.twig
Labels: Reviewed

#429 fix_footer_bottom
  templates/base.html.twig
Labels: Reviewed, Fix

#427 distinction bouton retour sidebar
  templates/client/edit.html.twig
Labels: Reviewed, Fix

#430 add icon
  templates/adminClient/_form.html.twig
Labels: Reviewed, Fix

#433 fix responsive home and scroll bar h
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed, Fix

#434 harmonisation btn
  templates/client/edit.html.twig
  templates/contact/index.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, Fix

#431 Dave toux Maine
  assets/styles/app.scss
  assets/styles/home.scss
  migrations/Version20220623143837.php
  migrations/Version20220628141015.php
  migrations/Version20220704074018.php
  migrations/Version20220704104515.php
  migrations/Version20220704120106.php
  migrations/Version20220704120504.php
  migrations/Version20220705103031.php
  migrations/Version20220705133709.php
  migrations/Version20220706102258.php
  migrations/Version20220706144331.php
  migrations/Version20220711145927.php
  migrations/Version20220713101524.php
  templates/adminClient/_form.html.twig
  templates/base.html.twig
  templates/client/edit.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#435 fix_div and button client
  templates/client/_form.html.twig
  templates/client/index.html.twig
Labels: Reviewed, Fix

#436 fix button admin
  templates/measurement/_delete_form.html.twig
  templates/measurement/_form.html.twig
  templates/service/_delete_form.html.twig
  templates/service/_form.html.twig
  templates/service/index.html.twig
Labels: Reviewed, Fix

#437 correction pictures
  assets/styles/home.scss
Labels: Reviewed, Fix

#438 position du texte plaquette entreprise
  templates/home/index.html.twig
Labels: Reviewed, Fix

#440 fixNl2br
  templates/email/email_user_to_admin.html.twig
Labels: Reviewed, Fix

#441 fixPlaquette
  assets/images/PlaquetteDeVente.pdf
Labels: Reviewed, Fix

#443 fixMailPassword
  config/packages/reset_password.yaml
  src/Controller/ResetPasswordController.php
Labels: Reviewed, Fix

#444 fix title service
  composer.json
  composer.lock
  templates/home/index.html.twig
Labels: Reviewed, Fix

#439 change type question
  migrations/Version20220718151617.php
  src/Entity/Service.php
  src/Form/ServiceType.php
Labels: Reviewed, Fix

#446 Fix bouton retour session
  templates/session/_form.html.twig
  templates/session/edit.html.twig
Labels: Reviewed, Fix

#447 fix min in table client
  templates/client/index.html.twig
Labels: Reviewed, Fix

#448 Dev->main
  assets/images/PlaquetteDeVente.pdf
  assets/styles/home.scss
  composer.json
  composer.lock
  config/packages/reset_password.yaml
  migrations/Version20220718151617.php
  src/Controller/ResetPasswordController.php
  src/Controller/ServiceController.php
  src/Entity/Service.php
  src/Form/ServiceType.php
  templates/client/_form.html.twig
  templates/client/index.html.twig
  templates/email/email_user_to_admin.html.twig
  templates/home/index.html.twig
  templates/measurement/_delete_form.html.twig
  templates/measurement/_form.html.twig
  templates/service/_delete_form.html.twig
  templates/service/_form.html.twig
  templates/service/index.html.twig
  templates/session/_form.html.twig
  templates/session/edit.html.twig
Labels: Reviewed

#449 fixModal
  templates/home/index.html.twig
Labels: Reviewed, Fix

#451 fix button back session
  templates/session/_form.html.twig
Labels: Reviewed, Fix

#453 fix_coaching_society
  assets/styles/home.scss
  assets/styles/variable.scss
  templates/home/index.html.twig
Labels: Reviewed, Fix

#454 add and use component
  templates/adminClient/edit.html.twig
  templates/component/_session_section.html.twig
Labels: Reviewed, Fix

#455 fix taille
  templates/client/index.html.twig
Labels: Reviewed, Fix

#456 coorection done
  assets/styles/home.scss
Labels: Reviewed, Fix

#457 Fix label sessoin form
  src/Form/SessionType.php
Labels: Reviewed, Fix

#458 fix_sidebar_and_client
  assets/styles/client.scss
  assets/styles/variable.scss
  templates/adminClient/edit.html.twig
  templates/client/edit.html.twig
  templates/client/index.html.twig
Labels: Reviewed, Fix, Conflit resolved

#459 fix_question
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed, Fix, Conflit resolved

#460 FixPoliceTitle
  assets/styles/variable.scss
  templates/home/index.html.twig
Labels: Reviewed, Fix

#461 add space in form and style
  assets/styles/admin.scss
  templates/session/_form.html.twig
Labels: Reviewed, Fix

#462 letter-spacing
  assets/styles/app.scss
  assets/styles/home.scss
Labels: Reviewed, Fix

#466 Fix kcal litre
  templates/client/index.html.twig
Labels: Reviewed, Fix

#464 fix_responsive_tablette
  templates/client/_form.html.twig
  templates/client/edit.html.twig
  templates/client/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Fix, Conflit resolved

#468 bouton_resaux
  templates/component/_footer.html.twig
Labels: Reviewed, Fix

#467 FIX_INT_HYDRATATION
  migrations/Version20220726141137.php
  src/Entity/Client.php
  src/Form/ClientType.php
  templates/client/index.html.twig
Labels: Reviewed, Corrections done, Help wanted, Conflit resolved

#463 DEV TO MAIN
  assets/styles/admin.scss
  assets/styles/app.scss
  assets/styles/client.scss
  assets/styles/home.scss
  assets/styles/variable.scss
  migrations/Version20220726141137.php
  src/DataFixtures/ServiceFixtures.php
  src/Entity/Client.php
  src/Form/ClientType.php
  src/Form/ExerciseType.php
  src/Form/SessionType.php
  templates/adminClient/edit.html.twig
  templates/client/_form.html.twig
  templates/client/edit.html.twig
  templates/client/index.html.twig
  templates/component/_footer.html.twig
  templates/component/_session_section.html.twig
  templates/exercise/index.html.twig
  templates/home/index.html.twig
  templates/session/_form.html.twig
Labels: Reviewed

#469 fix error photo
  migrations/Version20220727095834.php
  src/Controller/ServiceController.php
  src/Entity/Service.php
Labels: Reviewed, Fix

#470 Fix respons admin index
  templates/user/index.html.twig
Labels: Reviewed, Fix

#473 fix_placeholder_client
  assets/images/placeholderClient.jpg
Labels: Reviewed, Fix

#471 fix_responsive_admin_nutrition
  templates/adminClient/edit.html.twig
Labels: Reviewed, Corrections done, Fix

#472 Fix button admin
  src/Controller/NutritionMealController.php
Labels: Reviewed, Fix

#474 Border start
  templates/adminClient/_form.html.twig
Labels: Reviewed, Fix

#475 fix_edit_profil_client
  templates/client/edit.html.twig
Labels: Reviewed, Fix

#477 fix_flash
  assets/styles/app.scss
  templates/component/_flashes.html.twig
Labels: Reviewed, Fix

#478 style client
  templates/client/index.html.twig
  templates/component/_client_sidebar.html.twig
  templates/component/_measurement_client.html.twig
Labels: Reviewed, Fix

#476 fixPathSocial
  templates/component/_footer.html.twig
Labels: Reviewed, Fix, Conflit resolved

#480 Fix espacement div
  templates/adminClient/edit.html.twig
  templates/component/_session_section.html.twig
Labels: Reviewed, Conflit resolved

#481 fix_liste_client
  templates/user/index.html.twig
Labels: Rewind needed, Fix

#482 correction style
  assets/styles/home.scss
  templates/client/index.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Fix

#483 style mdp oublier
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
Labels: Reviewed, Fix

#479 Dev to main
  assets/images/placeholderClient.jpg
  assets/styles/app.scss
  assets/styles/home.scss
  migrations/Version20220727095834.php
  src/Controller/NutritionMealController.php
  src/Controller/ServiceController.php
  src/Entity/Service.php
  templates/adminClient/_form.html.twig
  templates/adminClient/edit.html.twig
  templates/client/edit.html.twig
  templates/client/index.html.twig
  templates/component/_client_sidebar.html.twig
  templates/component/_flashes.html.twig
  templates/component/_footer.html.twig
  templates/component/_measurement_client.html.twig
  templates/component/_session_section.html.twig
  templates/home/index.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/user/index.html.twig
Labels: Reviewed

#484 fix_nutrition
  templates/adminClient/edit.html.twig
Labels: Reviewed, Fix
