Repository WildCodeSchool/2022-03-php-orleans-project-paleolife, pull requests merged in 2022-06, with the labels that each got.

#1 initialisation
  assets/app.js
  assets/styles/_wcs.scss
  assets/styles/app.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#2 Dev to main
  assets/app.js
  assets/styles/_wcs.scss
  assets/styles/app.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#25 S01 us06view service crud
  migrations/Version20220608100102.php
  src/Controller/ServiceController.php
  src/DataFixtures/ServiceFixtures.php
  src/Entity/Service.php
  src/Form/ServiceType.php
  src/Repository/ServiceRepository.php
  templates/service/_delete_form.html.twig
  templates/service/_form.html.twig
  templates/service/edit.html.twig
  templates/service/index.html.twig
  templates/service/new.html.twig
Labels: Reviewed, Fix

#26 create card presentation
  assets/images/presentation.jpg
  assets/styles/home.scss
  templates/base.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed, Conflit resolved

#32 delete crud service
  templates/service/_delete_form.html.twig
Labels: Reviewed, Corrections done

#31 add crud service
  composer.json
  composer.lock
  config/packages/twig.yaml
  src/Entity/Service.php
  src/Form/ServiceType.php
  templates/service/_form.html.twig
  templates/service/new.html.twig
Labels: Reviewed, Corrections done

#35 trad edit
  templates/service/edit.html.twig
Labels: Reviewed

#37 fix id not blank
  src/Entity/Service.php
Labels: Reviewed

#30 navbarpaleolife
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/images/Logo.png
  assets/images/Logofeuille.png
  templates/base.html.twig
  templates/component/_admin_navbar.html.twig
  templates/component/_navbar.html.twig
Labels: Reviewed, Conflit resolved

#38 fix style like add
  templates/service/edit.html.twig
Labels: Reviewed

#40 fix nav
  templates/component/_navbar.html.twig
Labels: Reviewed

#41 fix migration
  migrations/Version20220608100553.php
Labels: Reviewed

#39 Dev to main 2
  .env
  .github/workflows/main.yml
  .gitignore
  assets/app.js
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/images/Logo.png
  assets/images/Logofeuille.png
  assets/images/presentation.jpg
  assets/styles/home.scss
  composer.json
  composer.lock
  config/packages/mailer.yaml
  config/packages/twig.yaml
  config/services.yaml
  migrations/Version20220608100102.php
  package.json
  src/Controller/ContactController.php
  src/Controller/ServiceController.php
  src/DataFixtures/ServiceFixtures.php
  src/Entity/Contact.php
  src/Entity/Service.php
  src/Form/ContactType.php
  src/Form/ServiceType.php
  src/Repository/ServiceRepository.php
  templates/base.html.twig
  templates/component/_admin_navbar.html.twig
  templates/component/_footer.html.twig
  templates/component/_navbar.html.twig
  templates/contact/index.html.twig
  templates/email/base.html.twig
  templates/email/email_user_to_admin.html.twig
  templates/home/index.html.twig
  templates/service/_delete_form.html.twig
  templates/service/_form.html.twig
  templates/service/edit.html.twig
  templates/service/index.html.twig
  templates/service/new.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#34 S01US2_imgAccueil
  assets/images/home.png
  assets/styles/app.scss
  assets/styles/home.scss
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Conflit resolved

#74 Fix_footer
  templates/component/_footer.html.twig
Labels: Reviewed

#75 Fix_navbar
  assets/styles/app.scss
  assets/styles/navbar.scss
  templates/component/_navbar.html.twig
Labels: Reviewed, Fix

#77 Fix presentation
  assets/images/presentation.jpg
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variable.scss
  templates/home/index.html.twig
Labels: Reviewed, Conflit resolved

#72 S2 us19 login
  composer.json
  composer.lock
  config/packages/security.yaml
  migrations/Version20220612225027.php
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/login/index.html.twig
Labels: Reviewed, Corrections done

#80 dev to main
  assets/images/home.png
  assets/images/presentation.jpg
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/variable.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  migrations/Version20220612225027.php
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/base.html.twig
  templates/component/_footer.html.twig
  templates/component/_navbar.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
Labels: Reviewed

#83 edit form and style
  composer.json
  composer.lock
  src/Entity/Exercise.php
  src/Form/ExerciseType.php
  symfony.lock
  templates/exercise/_form.html.twig
  templates/exercise/edit.html.twig
  templates/exercise/index.html.twig
Labels: Reviewed, Corrections done

#81 S02 U34 view objectif
  migrations/Version20220615122940.php
  src/Controller/ObjectiveController.php
  src/DataFixtures/ObjectiveFixtures.php
  src/Entity/Objective.php
  src/Form/ObjectiveType.php
  src/Repository/ObjectiveRepository.php
  templates/objective/_delete_form.html.twig
  templates/objective/_form.html.twig
  templates/objective/edit.html.twig
  templates/objective/index.html.twig
  templates/objective/new.html.twig
  templates/objective/show.html.twig
Labels: Reviewed, Corrections done

#84 style and trad add
  templates/exercise/_form.html.twig
  templates/exercise/index.html.twig
  templates/exercise/new.html.twig
Labels: Reviewed, Conflit resolved

#85 trad delete
  templates/exercise/_delete_form.html.twig
Labels: Reviewed, Corrections done

#88 Dev to Main
  composer.json
  composer.lock
  migrations/Version20220615072619.php
  migrations/Version20220615122940.php
  src/Controller/ExerciseController.php
  src/Controller/ObjectiveController.php
  src/DataFixtures/ExerciseFixtures.php
  src/DataFixtures/ObjectiveFixtures.php
  src/Entity/Exercise.php
  src/Entity/Objective.php
  src/Form/ExerciseType.php
  src/Form/ObjectiveType.php
  src/Repository/ExerciseRepository.php
  src/Repository/ObjectiveRepository.php
  symfony.lock
  templates/exercise/_delete_form.html.twig
  templates/exercise/_form.html.twig
  templates/exercise/edit.html.twig
  templates/exercise/index.html.twig
  templates/exercise/new.html.twig
  templates/objective/_delete_form.html.twig
  templates/objective/_form.html.twig
  templates/objective/edit.html.twig
  templates/objective/index.html.twig
  templates/objective/new.html.twig
  templates/objective/show.html.twig
Labels: Reviewed

#90 fix_style_contact
  templates/contact/index.html.twig
Labels: Reviewed, Fix

#93 fix_footer_bottom
  assets/styles/app.scss
  templates/base.html.twig
Labels: Reviewed, Fix

#82 S2US17Inscriptions
  .github/workflows/main.yml
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, Conflit resolved

#96 create edit objective
  templates/objective/edit.html.twig
Labels: Reviewed, Conflit resolved

#97 Fix card service
  templates/home/index.html.twig
Labels: Reviewed

#98 create button delete objective
  templates/objective/_delete_form.html.twig
  templates/objective/index.html.twig
Labels: Reviewed

#86 S2US38_add_session
  migrations/Version20220615081505.php
  src/Controller/SessionController.php
  src/DataFixtures/SessionFixtures.php
  src/Entity/Session.php
  src/Form/SessionType.php
  src/Repository/SessionRepository.php
  templates/session/_delete_form.html.twig
  templates/session/_form.html.twig
  templates/session/edit.html.twig
  templates/session/index.html.twig
  templates/session/new.html.twig
  templates/session/show.html.twig
Labels: Reviewed, Corrections done

#99 final style buuton for cohrence with other
  templates/exercise/_form.html.twig
  templates/exercise/edit.html.twig
  templates/exercise/index.html.twig
  templates/exercise/new.html.twig
  templates/service/_delete_form.html.twig
  templates/service/_form.html.twig
  templates/service/edit.html.twig
  templates/service/index.html.twig
  templates/service/new.html.twig
Labels: Reviewed, Corrections done

#102 fix migration
  migrations/Version20220615081505.php
  migrations/Version20220615122940.php
Labels: Reviewed

#104 fix migration is_verified
  migrations/Version20220616130617.php
Labels: Reviewed

#108 change container
  templates/contact/index.html.twig
Labels: Reviewed

#109 Fix register
  src/Controller/RegistrationController.php
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#111 fix_card_home
  templates/home/index.html.twig
Labels: Reviewed

#113 Dev to main 3
  migrations/Version20220616130617.php
  src/Controller/RegistrationController.php
  templates/base.html.twig
  templates/component/_footer.html.twig
  templates/component/_navbar.html.twig
  templates/contact/index.html.twig
  templates/exercise/_form.html.twig
  templates/exercise/edit.html.twig
  templates/exercise/index.html.twig
  templates/exercise/new.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  templates/login/index.html.twig
  templates/objective/edit.html.twig
  templates/objective/index.html.twig
  templates/objective/new.html.twig
  templates/objective/show.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/service/_form.html.twig
  templates/service/index.html.twig
  templates/service/new.html.twig
  templates/session/_delete_form.html.twig
  templates/session/_form.html.twig
  templates/session/edit.html.twig
  templates/session/index.html.twig
  templates/session/new.html.twig
  templates/session/show.html.twig
Labels: Reviewed

#117 S2US41_delete_session
  templates/session/_delete_form.html.twig
Labels: Reviewed

#119 fix_style_service_admin
  templates/service/_delete_form.html.twig
  templates/service/_form.html.twig
  templates/service/index.html.twig
  templates/service/new.html.twig
Labels: Reviewed, Fix

#116 S2US39_edit_session
  src/Controller/SessionController.php
  templates/session/_form.html.twig
  templates/session/edit.html.twig
  templates/session/index.html.twig
Labels: Reviewed

#123 Fix objective
  src/Controller/ObjectiveController.php
  templates/objective/_delete_form.html.twig
  templates/objective/_form.html.twig
  templates/objective/edit.html.twig
  templates/objective/index.html.twig
Labels: Reviewed, Fix

#124 fix_style_exercise_admin
  templates/exercise/_delete_form.html.twig
  templates/exercise/_form.html.twig
  templates/exercise/edit.html.twig
  templates/exercise/index.html.twig
  templates/exercise/new.html.twig
Labels: Reviewed, Fix

#127 fix home
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variable.scss
  templates/base.html.twig
  templates/component/_navbar.html.twig
  templates/home/index.html.twig
Labels: Reviewed, Fix

#147 change container style
  templates/contact/index.html.twig
Labels: Reviewed, Fix

#141 S3 us53 user view
  migrations/Version20220620084444.php
  src/Controller/UserController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Repository/UserRepository.php
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Reviewed, Corrections done

#150 fix_login_style
  templates/login/index.html.twig
Labels: Reviewed, Fix

#154 fix_registration_style
  templates/registration/register.html.twig
Labels: Reviewed, Corrections done, Fix

#153 S3US31DeleteUser
  templates/user/_delete_form.html.twig
  templates/user/index.html.twig
Labels: Reviewed, Corrections done

#160 fix_registration
  src/Entity/User.php
Labels: Reviewed, Fix

#158 Fix flash contact
  src/Controller/ContactController.php
  templates/base.html.twig
  templates/component/_flashes.html.twig
Labels: Reviewed, Corrections done, Fix

#162 fix_flash_registration
  src/Controller/RegistrationController.php
Labels: Reviewed, Corrections done, Fix

#163 S04 us65 navbar client
  templates/component/_navbar_client.html.twig
  templates/layoutClient.html.twig
Labels: Reviewed

#167 fix_presentation_style
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed, Fix

#171 secure route
  config/packages/security.yaml
  src/Controller/ExerciseController.php
  src/Controller/ObjectiveController.php
  src/Controller/ServiceController.php
  src/Controller/SessionController.php
  src/Controller/UserController.php
Labels: Reviewed

#172 delete table objective and all
  migrations/Version20220615122940.php
  src/Controller/ObjectiveController.php
  src/DataFixtures/ObjectiveFixtures.php
  src/Entity/Objective.php
  src/Form/ObjectiveType.php
  src/Repository/ObjectiveRepository.php
  templates/objective/_delete_form.html.twig
  templates/objective/_form.html.twig
  templates/objective/edit.html.twig
  templates/objective/index.html.twig
  templates/objective/new.html.twig
  templates/objective/show.html.twig
Labels: Reviewed, Conflit resolved

#175 Dev to Main
  config/packages/security.yaml
  migrations/Version20220615122940.php
  migrations/Version20220616130617.php
  migrations/Version20220620084444.php
  migrations/Version20220621151704.php
  migrations/Version20220623143837.php
  src/Controller/ClientController.php
  src/Controller/ExerciseController.php
  src/Controller/ObjectiveController.php
  src/Controller/ServiceController.php
  src/Controller/SessionController.php
  src/Controller/UserController.php
  src/DataFixtures/ClientFixtures.php
  src/DataFixtures/ObjectiveFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Client.php
  src/Entity/User.php
  src/Form/ClientType.php
  src/Form/UserType.php
  src/Repository/ClientRepository.php
  src/Repository/ObjectiveRepository.php
  templates/client/_form.html.twig
  templates/client/edit.html.twig
  templates/objective/_delete_form.html.twig
  templates/objective/edit.html.twig
  templates/objective/index.html.twig
  templates/objective/new.html.twig
  templates/objective/show.html.twig
  templates/user/_delete_form.html.twig
  templates/user/index.html.twig
Labels: Reviewed

#177 add admin navbar for client
  templates/component/_admin_navbar.html.twig
  templates/user/index.html.twig
Labels: Reviewed

#183 create a redirect after logging in as admin
  config/packages/security.yaml
  src/Controller/LoginController.php
Labels: Reviewed

#185 correcrion redirect client
  .gitignore
  src/Controller/LoginController.php
Labels: Reviewed, Corrections done

#194 view all objectiv client
  templates/client/index.html.twig
Labels: Reviewed
